before_install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.36.1/hugo_0.36.1_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
script:
- hugo
deploy:
- provider: script
  skip_cleanup: true
  script: chmod +x ./deploy.sh && ./deploy.sh
  on:
    branch: master
before_deploy:
- openssl aes-256-cbc -K $encrypted_b30cc9581a71_key -iv $encrypted_b30cc9581a71_iv
  -in deploy_tmp.enc -out deploy_tmp -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_tmp
- ssh-add /tmp/deploy_tmp
- ssh-keyscan vul.haoxp.xyz >> ~/.ssh/known_hosts
