before_install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.36.1/hugo_0.36.1_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb

# Build the website
script:
  - hugo

deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x ./deploy.sh && ./deploy.sh
    on:
      branch: master

before_deploy:
- openssl aes-256-cbc -K $encrypted_fbf95acb6d79_key -iv $encrypted_fbf95acb6d79_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- ssh-keyscan vul.haoxp.xyz >> ~/.ssh/known_hosts