before_install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.36.1/hugo_0.36.1_Linux-64bit.deb
- sudo dpkg -i hugo*.deb

script:
- hugo

before_deploy:
- echo blog.haoxp.xyz > public/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public 
  target-branch: gh-pages
  on:
    branch: master 
