baseURL = "/"
languageCode = "en-us"
title = "Xiangpeng Hao"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/HaoPatrick\">Xiangpeng Hao</a> 2019"
googleAnalytics = "UA-66103952-7"
disqusShortname = "patrick-blog"
[params.social]
ahome = "www.haoxp.xyz"
github = "HaoPatrick"
linkedin = "hao-xiangpeng"

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Blog - Xiangpeng Hao" # Title for home page
poweredby = false # Adds powered by hugo and kiss below Copyright
related = false # Includes related articles at the bottom of the article
