baseURL = "https://blog.haoxp.xyz/"
languageCode = "en-us"
title = "Xiangpeng Hao"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/HaoPatrick\">Xiangpeng Hao</a> 2018"
[params.social]
github = "HaoPatrick"
linkedin = "hao-xiangpeng"

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Hao" # Title for home page
poweredby = false # Adds powered by hugo and kiss below Copyright
related = false # Includes related articles at the bottom of the article

