baseURL = "/"
languageCode = "en-us"
title = "Xiangpeng Hao"
theme = "kiss"
copyright = "<a href=\"https://www.haoxp.xyz\">Xiangpeng Hao</a> 2019"
googleAnalytics = "UA-66103952-7"

[params.social]
rss = "blog.haoxp.xyz/index.xml"
ahome = "haoxp.xyz"
github = "XiangpengHao"
linkedin = "hao-xiangpeng"
telegram = "t.me/newsathlh"

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Blog - Xiangpeng Hao" # Title for home page
poweredby = false # Adds powered by hugo and kiss below Copyright
related = false # Includes related articles at the bottom of the article
